strategy: "fsdp"
sharding_strategy: "full_shard"

gradient_checkpointing: False
cpu_offload: False
offload_pin_memory: False
reshard_after_forward: True

enable_gradient_accumulation: True
forward_prefetch: False
limit_all_gathers: False
backward_prefetch: null
use_orig_params: False
use_liger_kernel: False

fsdp_size: -1

mixed_precision:
  param_dtype: null
  reduce_dtype: null
  buffer_dtype: null

amp_autocast:
  enabled: False
  precision: "bf16"

grad_scaler:
  enabled: False
